# moon: The build system and package manager for MoonBit.
# Copyright (C) 2024 International Digital Economy Academy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - rustica

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Install dependencies
        run: |
          apt update && apt install -y software-properties-common curl unzip build-essential git sudo coreutils

      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@1.80.0

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - run: |
          git config --global --add safe.directory "$(pwd)"
          git status

      - name: Build
        run: |
          cargo build --features moongres --release --bin moon
          mkdir -p dist/MoonGRES/nightly/Linux-x86_64/
          tar -czf dist/MoonGRES/nightly/Linux-x86_64/moon.tar.gz -C target/release moon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: moon-Linux-x86_64
          path: dist

  upload:
    runs-on: ubuntu-latest
    needs: [ ubuntu-build ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: moon-*
          merge-multiple: true
          path: dist

      - name: Install rclone
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf << EOF
          [r2]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
          endpoint = ${{ secrets.R2_ENDPOINT }}
          acl = public-read
          EOF

      - name: Upload to R2
        run: |
          rclone copy dist r2:${{ secrets.R2_BUCKET_NAME }} --progress
